version: '3'

services:
  migration:
    build:
      context: ../
      dockerfile: build/builder/Dockerfile.migrate
    volumes:
      - ../configs/migration:/work/migration
    tty: true
  db:
    image: postgres:12.5-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=suburi
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=suburi_db
    ports:
      - 15432:5432
  server:
    build:
      context: ../
      dockerfile: build/builder/Dockerfile.server
    volumes:
      - ../cmd/gowiki:/go/src/github.com/suburi-dev/gowiki/cmd/gowiki
      - ../internal:/go/src/github.com/suburi-dev/gowiki/internal
    ports:
      - 9000:9000
    container_name: server
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=suburi
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=suburi_db
    restart: always
volumes:
  db-data:
    driver: local
